### ISSUE TITLE
How to use blast function on mrbait?

### ISSUE THREAD

**Issue by GreenTomjerry** [tkchafin/mrbait#22]
Dear Mr. Tyler Chafin,

I am a master’s student at the University of Queensland, and I am attempting to generate a set of probes using mrbait and subsequently use the blast functionality within your software for further probe filtering. However, I have encountered difficulties in calling my deployed blast through mrbait. Could I inquire about the correct procedure for utilizing it?

From the help prompts of your software, I came across the following information:

BLAST Parameters (**use when --select_b or --select_r = “blast”**):

        --blastdb       : Path and prefix to existing Blast database to use

       ........

My understanding is that I need to use the parameter: --select blast --blastdb as input.

Therefore, I composed the following command:

mrbait -A /home/gujiarui1998/methyfile/targeted_5000bpx10_forblastn.fa -b 120 -o nm_1 -T 4 --select_b blast --blastdb /home/gujiarui1998/ncbi-blast-2.15.0+/db/hg19

However, I received the following error: ValueError: Invalid option “‘blast’” for <–select_b>

When I reviewed the menu code, I found the following segment:

#Bait selection options

                  elif opt=='s' or opt=='select_b':
                        subopts = re.split('=|,',arg)
                        self.select_b = (subopts[0]).lower()
                        **chars = (['tile', 'center', 'flank', 'calc'])
                        if self.select_b not in chars:
                              raise ValueError("Invalid option \"%r\" for <--select_b>" % self.select_b)**

The highlighted part indicates that -s does not accept blast parameters!

I have attempted various approaches, such as removing --select_b blast, which allowed the code to run but did not initiate the blast.

I have deployed blast and established the database, but I am unable to proceed with the usage.

I have thoroughly examined your manual, but unfortunately, there are no tutorials on using this method:

![image](https://github.com/tkchafin/mrbait/assets/80318243/294ac1af-0d4c-4801-a3d3-17206f2e7698)

I am utterly perplexed, and it seems I will be unable to accomplish what I set out to do, and I may have to switch to a different software. Could you please advise me on how to modify my code to achieve the desired outcome?

mrbait -A /home/gujiarui1998/methyfile/targeted_5000bpx10_forblastn.fa -b 120 -o nm_1 -T 4 --select_b blast --blastdb /home/gujiarui1998/ncbi-blast-2.15.0+/db/hg19

Yours faithfully,
Jiarui Gu

**Comment by tkchafin** [comment]
Hi Jiarui, The blast options can only be used for locus/bait filtering, so the --filter_b or --filter_r options. If you call using the -h flag you should be able to see all of the options for filtering in the help menu

**Comment by GreenTomjerry** [comment]
> Hi Jiarui, The blast options can only be used for locus/bait filtering, so the --filter_b or --filter_r options. If you call using the -h flag you should be able to see all of the options for filtering in the help menu

mrbait -A /home/gujiarui1998/methyfile/targeted_5000bpx10_forblastn.fa -b 120 -o cnm -T 4  --filter_b **–blastdb /home/gujiarui1998/ncbi-blast-2.15.0+/db/hg19**

**Reply: Invalid option '–blastdb' for <--filter_b>!**
Invalid options: Exiting program. Please see manual or use <--help>

 -f,--filter_b   : Include any criteria used to filter ALL baits
                --Options
                        mask=[x]     : Maximum of "x" proportion of masked bases allowed
                        gc=[x,y]     : Proportion of G/C bases between "x" (min) and "y" (max)
                        pw=[i,q]     : Pairwise alignment, removing when "i" identity in "q" proportion
                        rc=[i,q]     : Pairwise alignment against reverse-complements (see -r pw=[i,q])
                        blast_i=[i,q]: Only retain hits over "i" identity and "q" query coverage to provided db
                        **blast_x=[i,q]: Remove hits over "i" identity and "q" query coverage to provided db**
                        blast_a=[i,q]: Remove targets having >1 hits with "i" identity and "q" query coverage to provided db
                        rand=[x]     : Randomly retain "x" baits
                        bed_x        : Exclude baits within "d" distance of BED records
                        bed_i        : Only include baits within "d" distance of BED records

How can I define –blastdb? I want to filter probes which can have only one hit on ref genome, what shall I do？

**Comment by GreenTomjerry** [comment]
> 嗨，家瑞， 爆炸选项只能用于轨迹/诱饵过滤，所以 --filter_b 或 --filter_r 选项。如果使用 -h 标志进行调用，您应该能够在帮助菜单中看到所有用于过滤的选项

Invalid option '–-blast_i' for <--filter_b>!
Invalid options: Exiting program. Please see manual or use <--help>

**Comment by GreenTomjerry** [comment]
**-f,--filter_b : Include any criteria used to filter ALL baits
--Options
blast_i=[i,q]: Only retain hits over "i" identity and "q" query coverage to provided db**

mrbait -A /home/gujiarui1998/methyfile/targeted_5000bpx10_forblastn.fa -b 120 -o cnm -T 4  --filter_b –-blast_i=[80,80]
reply:
**Invalid option '–-blast_i' for <--filter_b>!**
Invalid options: Exiting program. Please see manual or use <--help>
